- pom.xml
- src/main/java/hudson/security/LDAPSecurityRealm.java
> Enable FindBugs in the plugin

- src/main/java/hudson/security/LDAPSecurityRealm.java
Follow-up to #4 ...
The Javadoc has not been released yet, so the change should not break anything on the user side.
@reviewbybees @KostyaSha
> Throw IllegalStateException instead of the Error

- pom.xml
- src/main/java/hudson/security/LDAPSecurityRealm.java
@reviewbybees
* Upgraded to parent pom 2.3
* Fixed javadoc issue
> [JENKINS-33300] Upgrade to parent pom 2.3

- pom.xml
- src/main/resources/jenkins/security/plugins/ldap/FromUserRecordLDAPGroupMembershipStrategy/config.jelly
- src/test/java/hudson/security/LDAPSecurityRealm_Test.java
See [JENKINS-30588](https://issues.jenkins-ci.org/browse/JENKINS-30588)
This PR picks the relevant commit https://github.com/jenkinsci/ldap-plugin/pull/3/commits/1b87f243a70e356b40b0c3f52a039acbb9d48b61 from https://github.com/jenkinsci/ldap-plugin/pull/3, adds a test, and perform miscellaneous updates to the POM.
@reviewbybees
> [JENKINS-30588] Value for "Group membership attribute" not saved

- Jenkinsfile
- pom.xml
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/resources/hudson/security/LDAPSecurityRealm/EnvironmentProperty/config.jelly
- src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
Also add a Jenkinsfile
@reviewbybees
> Update baseline version of Jenkins to 1.625.3

- src/main/java/hudson/security/LDAPSecurityRealm.java
[JENKINS-42030](https://issues.jenkins-ci.org/browse/JENKINS-42030)
@reviewbybees
> [JENKINS-42030] Throw only declared exception types

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/main/resources/jenkins/security/plugins/ldap/Messages.properties
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
- src/test/java/hudson/security/LdapMultiEmbedded2Test.java
- src/test/java/jenkins/security/plugins/ldap/LDAPConfigurationTest.java
See discussion in #17 
@reviewbybees esp. @stephenc
> [JENKINS-44743] Use a compound key to identify server configurations

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
- src/main/resources/jenkins/security/plugins/ldap/LDAPConfiguration/config.jelly
- src/test/java/hudson/security/LDAPEmbeddedTest.java
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
> [Fix JENKINS-45431] Moved the config snippet to the correct jelly

- Jenkinsfile
- pom.xml
> Some updates

- pom.xml
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/main/java/jenkins/security/plugins/ldap/LDAPExtendedTemplate.java
- src/main/resources/jenkins/security/plugins/ldap/Messages.properties
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
- src/test/java/hudson/security/LdapMultiEmbeddedTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPConfigurationTest.java
Modernize pom to latest parent POM should help with #35
> Modernize pom

- README.md
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
- src/main/resources/hudson/security/LDAPSecurityRealm/help-groupMembershipFilter.html
- src/main/resources/jenkins/security/plugins/ldap/LDAPConfiguration/help-groupSearchBase.html
Forgotten in #46. Not totally sure about correctness of revised text, as I do not really understand what these options are for; just guessing based on similar-sounding fields and so on.
> Removing some documentation related to BeanBuilder

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
#49 plus assorted code cleanups.
> Spring cleaning

- README.md
- pom.xml
- src/main/java/hudson/security/GeneralizedTime.java
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/hudson/security/UserAttributesHelper.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
- src/test/java/hudson/security/docker/MultiServerTest.java
- src/test/java/hudson/security/docker/PlanetExpressTest.java
- src/test/resources/hudson/security/planetexpressWithPPolicy.ldif
Builds on top of #49, ~so diff against Jesse's branch for an easier view: https://github.com/jglick/ldap-plugin/compare/spring-5303-new...jvz:JENKINS-55813-spring-security~
https://issues.jenkins.io/browse/JENKINS-55813
> [JENKINS-55813] Add support for LDAP password policy attributes (account locking)

- pom.xml
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/hudson/security/UserAttributesHelper.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
Amends #59 to not rely on patches elsewhere. See https://github.com/jenkinsci/jenkins/pull/4925#issuecomment-733116395 for discussion.
> Throw AccountStatusException rather than setting flags on LdapUserDetails

- README.md
- src/main/resources/hudson/security/LDAPSecurityRealm/help-cache.html
Changing master to controller on documentation as part of [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398)
> [JENKINS-65398] terminology update

- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- for anonymous check we may have not the right to getAttributes so we must simply ensure we can connect
- timeout should be configurable, simplify some code as well
> simplify connectivity check

- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
Java 8 includes a built-in Base64 encoder, so there is no reason to depend on a third-party library. Using the built-in Java Platform functionality simplifies maintenance.
> Drop dependency on Commons Codec

- .mvn/extensions.xml
- pom.xml
- src/test/java/jenkins/security/plugins/ldap/LDAPDNEscapingTest.java
A release of this would help us do Java 17 testing of this plugin. CC @olamy
> Update plugin parent POM and BOM

- pom.xml
Upgrade jenkins version to latest lts and also the parent pom to latest release
As a side effect we also get an updated Spring version aligned with the one in latest cores
I checked all tests pass, not sure if there is something else to test here
> Update jenkins baseline and parent pom to 2.346.1 and 4.45

- src/main/java/hudson/security/GeneralizedTime.java
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
- src/main/java/jenkins/security/plugins/ldap/FromUserRecordLDAPGroupMembershipStrategy.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/main/java/jenkins/security/plugins/ldap/LDAPExtendedTemplate.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
- src/test/java/hudson/security/LdapMultiEmbedded2Test.java
- src/test/java/hudson/security/LdapMultiEmbeddedTest.java
- src/test/java/hudson/security/docker/MultiServerTest.java
- src/test/java/hudson/security/docker/PlanetExpressTest.java
- src/test/java/jenkins/security/plugins/ldap/CasCTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPConfigurationTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPDNEscapingTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPExtendedTemplateTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPRule.java
Replaces usages of deprecated APIs and some further modernizations.
--------------
> Replace deprecated APIs and modernization

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
- src/test/java/hudson/security/LDAPEmbeddedTest.java
Fix issues for 1.12 based of 2.346.x as discussed in https://github.com/jenkinsci/ldap-plugin/pull/185 (cherry picked commits with the fix for 2.346)
> [JENKINS-68748] Adapt Test LDAP functionality to 2.346.x

- src/test/java/hudson/security/LDAPSecurityRealmTest.java
See https://github.com/jenkinsci/jenkins/pull/7173#issuecomment-1368056507
This is forward and backwards compatible
> Adapt test to advanced component change in core

- README.md
This removes a few trailing white spaces and replace some non breaking space with normal spaces.
I have also adjusted some markdown link to avoid having the link title split over a newline.
- [NA] Link to relevant issues in GitHub or Jira
- [NA] Link to relevant pull requests, esp. upstream and downstream changes
- [NA] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Slightly improve README.md formatting

- src/main/java/hudson/security/LDAPSecurityRealm.java
_See #170 discussion._
/cc @basil 
------------------
> Use encoding of the request

- .mvn/extensions.xml
- Jenkinsfile
- pom.xml
Closes #221.
https://github.com/jenkinsci/ldap-plugin/pull/185#issuecomment-1451832377
> Update to 2.361.x

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
- src/test/java/hudson/security/LdapMultiEmbeddedTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPExtendedTemplateTest.java
Modernize some type related things.
```[tasklist]
```
> Modernize types

- src/main/resources/jenkins/security/plugins/ldap/validation/validate.jelly
- src/main/resources/jenkins/security/plugins/ldap/validation/validateButton.js
- src/main/resources/jenkins/security/plugins/ldap/validation/validateButtonOnClick.js
mvn test shows no error. Screenshots attached.
Before:
After:
```[tasklist]
```
Closes Issue: https://issues.jenkins.io/browse/JENKINS-72117
and https://issues.jenkins.io/browse/JENKINS-70529 (duplicate)
Remove onclick script according to the guidelines: https://www.jenkins.io/doc/developer/security/csp/#inline-event-handlers
> feat:remove-inline onclick handlers for validate button

- pom.xml
Initially added as part of https://github.com/jenkinsci/ldap-plugin/pull/146 to fix an upper-bound issue, it is no longer necessary, and makes dependabot nag about it.
```[tasklist]
```
> Remove slf4j-api override

- README.md
Removes information that's out of date after https://github.com/jenkinsci/jenkins/pull/5445
> Remove mention of bundled plugin from README

- README.md
- src/main/java/hudson/security/UserAttributesHelper.java
This change corrects the handling of the orclIsEnabled attribute to detect disabled accounts for Oracle Internet Directory (OID). This issue was originally reported in 2021 under <https://issues.jenkins.io/browse/JENKINS-65806>
First the issue was confirmed to still occur using the most recent LDAP plugin. When attempting to configure Jenkins to use LDAP with Oracle Internet Directory the Test LDAP Settings results will  show Login success and be able to list some user attributes and groups but report failures for Lookup and Lockout. The output is:
User lookup: failed for user "matt.heimer@oracle.com"
The user "matt.heimer@oracle.com" is administratively disabled.
The user "matt.heimer@oracle.com" may be unable to login with API tokens or SSH keys.
The user will have inconsistent …
> [JENKINS-65806] Correct handling of `orclIsEnabled` for Oracle Internet Directory

- .github/renovate.json
> Remove `src/test/java` exclusion from Renovate configuration
