jenkinsci/ldap-plugin

- pom.xml
In order to make the build of the plugin stable using baseline 2.0-rc-1, the parent pom to use must be 2.4+ where version 2.6 of the Jenkins Test Harness is picked up.
@reviewbybees
> Bump parent pom version to 2.6

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/test/java/hudson/security/LDAPSecurityRealm_Test.java
See [JENKINS-8152](https://issues.jenkins-ci.org/browse/JENKINS-8152)
The rootDN must be URI-encoded when included in the provider URL.
@reviewbybees
> [JENKINS-8152] Encode rootDN in provider URL.

- pom.xml
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
Ever since the CI builds were moved to [ci.jenkins.io](https://ci.jenkins.io/job/Plugins/job/ldap-plugin/job/master/) all builds have failed. Previously they were being built against Jenkins 1.625.3 on [jenkins.ci.cloudbees.com](https://jenkins.ci.cloudbees.com/job/plugins/job/ldap-plugin/), which worked correctly, but now they are being tested against the Jenkins default version and 2.32.3, which requires an updated version of the bouncycastle-api plugin.
Additionally, there is a simple test failure on Windows that appears to be the result of a UI change.
java.lang.AssertionError:` Button [Advanced...] not found
at hudson.security.LDAPSecurityRealmTest.getButtonByText(LDAPSecurityRealmTest.java:206)
at hudson.security.LDAPSecurityRealmTest.groupMembershipAttribute(LDAPSecurityRealmTest.ja …
> Fix test failures in CI builds

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/FromGroupSearchLDAPGroupMembershipStrategy.java
- src/main/java/jenkins/security/plugins/ldap/FromUserRecordLDAPGroupMembershipStrategy.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/main/java/jenkins/security/plugins/ldap/LDAPExtendedTemplate.java
- src/main/java/jenkins/security/plugins/ldap/LDAPGroupMembershipStrategy.java
- src/main/java/jenkins/security/plugins/ldap/LDAPSearchUtils.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
- src/test/java/hudson/security/LdapMultiEmbeddedTest.java
- src/test/java/jenkins/security/plugins/ldap/LDAPExtendedTemplateTest.java
See [JENKINS-21784](https://issues.jenkins-ci.org/browse/JENKINS-21784).
Adds support for `SecurityRealm#loadGroupByGroupname(String, boolean)` and `GroupDetails#getMembers()`.
@reviewbybees
> [JENKINS-21784] Add support for querying group membership

- .gitignore
- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
- src/main/resources/jenkins/security/plugins/ldap/LDAPConfiguration/config.jelly
- src/main/resources/jenkins/security/plugins/ldap/LDAPConfiguration/help-ignoreIfUnavailable.html
- src/test/java/hudson/security/LDAPSecurityRealmTest.java
- src/test/java/hudson/security/LdapMultiEmbeddedTest.java
See [JENKINS-48917](https://issues.jenkins-ci.org/browse/JENKINS-48917).
This change allows communication failures with LDAP servers (i.e., DataAccessException, AuthenticationServiceException) to be ignored so that the failed action will be reattempted with the next configuration.
@reviewbybees
> [JENKINS-48917] Add option to ignore LDAP servers if they are unavailable.

- pom.xml
Version 1.16 introduced a change ([JENKINS-21475](https://issues.jenkins-ci.org/browse/JENKINS-21475)) in the configuration file which is not backward compatible in terms of plugin downgrades. Although plugin downgrades are not usually supported and not granted to work, additions to the config file are just ignored and old features still work, but not in this case, because there is a structure change in the file which makes older plugin versions unable to know what to load from disk.
The compat warning message says: 
```
Warning: [...] and/or you may not be able to cleanly revert to the prior version without manually restoring old settings [...]
``` 
So I think changes for JENKINS-21475 justify the need of the `compatibleSinceVersion` flag here.
@reviewbybees esp. @rsandell @stephenc (who …
> Set the compatibleSinceVersion flag

- README.md
- pom.xml
- src/test/java/jenkins/security/plugins/ldap/CasCTest.java
- src/test/java/jenkins/security/plugins/ldap/CascSecurityRealmTest.java
- src/test/resources/jenkins/security/plugins/ldap/LDAPSecurityRealmTestNoSecret.yml
- src/test/resources/jenkins/security/plugins/ldap/LDAPSecurityRealmTestNoSecretExpected.yml
- src/test/resources/jenkins/security/plugins/ldap/casc.yml
I've added to the plugin the tests already done on [Configuration as Code plugin](https://github.com/jenkinsci/configuration-as-code-plugin) to test the JCasC compatibility on each release.
I've added some documentation on how to configure the plugin with CasC.
@rsandell @varyvol @alecharp @batmat
> Configuration as Code compatibility tests

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
See [JENKINS-61854](https://issues.jenkins-ci.org/browse/JENKINS-61854)
The dialog shown when pressing the **_Test LDAP Settings_** button of the ldap configuration was broken after Jenkins 2.214 because the check **_Enable Security_** was removed and the javascript was not working.
I've added a decision logic for Jenkins < 2.214 or >= 2.214
Tested manually with:
* `mvn hpi:run -Djenkins.version=2.230` (2.230) and
* `mvn hpi:run` (2.60.3)
> [JENKINS-61854] Fix ldap test button dialog on Jenkins > 2.214

- src/main/java/hudson/security/LDAPSecurityRealm.java
My previous fix wasn't enough. On java code it's also needed to get the correct element from the json based on the Jenkins version.
Now I managed to configure a ldap server with all needed and all checks are green.
> [JENKINS-61854] Get the json value depending on the Jenkins version

- src/test/java/hudson/security/docker/MultiServerTest.java
- src/test/java/hudson/security/docker/PlanetExpressTest.java
These started failing regularly recently.
BTW the Dockerized tests are _flaky_ on Linux too: CI shows several recent failures like
```
starting slapd on port 389 and 636...
5ea00f09 @(#) $OpenLDAP: slapd  (Aug 10 2019 19:17:00) $
Debian OpenLDAP Maintainers <pkg-openldap-devel@lists.alioth.debian.org>
5ea00f0a ch_calloc of 1048576 elems of 704 bytes failed
slapd: ../../../../servers/slapd/ch_malloc.c:107: ch_calloc: Assertion `0' failed.
```
> Suppress Dockerized tests on Windows

- .mvn/extensions.xml
- .mvn/maven.config
- Jenkinsfile
- pom.xml
Apparently suffices to offer compatibility with https://github.com/jenkinsci/jenkins/pull/4848 while still running on current Jenkins releases.
> Compatibility with Spring Security

- README.md
Reviewing a possible authentication issue I found a problem with how Java8 treats the `Organization Units` in the `principalDN`.
The authentication process in the plugin use the class `LdapTemplate` and the method `public Object execute(LdapCallback callback) throws DataAccessException` for performing the connection to the LDAP for the authentication process. 
The `principalDn` generated by the class `LdapSearchEnumeration` of the package `com.sun.jndi.ldap` in the JDK-8 has an `"` character at the beginning and at the end if the `ou` has an `/` character in the name.
In our example an user with the following path:
```
cn=user1,cn=group1,ou=some word / another word,dc=example,dc=org
```
Generates the following `principalDN`:
```
"cn=user1,cn=group1,ou=some word / another …
```
> Tip for avoid foward slash character in the Organization Units

- src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
- src/main/resources/jenkins/security/plugins/ldap/validation/validate.jelly
Follow up on [JENKINS-62809](https://issues.jenkins.io/browse/JENKINS-62809)
This PR removes all traces of tabular markup from the plugin.  The minimum jenkins version is 2.266 so no need to keep backwards compatibility.
> Remove traces of tabular markup from LDAP forms

- src/test/resources/hudson/security/docker/PlanetExpressTest/PlanetExpress/Dockerfile
The docker image used to have a LDAP server for the tests was changed recently. And using `latest` couldn't warn us of that. However, using the digest, we will at least know when this image is not available anymore.
This is required for PCT run.
> Use digest to get base ldap docker image

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/hudson/security/UserAttributesHelper.java
@rsandell 
https://issues.jenkins.io/browse/JENKINS-64629
Unfortunately, spotbugs does not appear to be sophisticated enough to have prevented this.
> JENKINS-64629: Fix "null" in error message

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/main/java/jenkins/security/plugins/ldap/LDAPConfiguration.java
Includes the rootDN in the initial request to the server to check for availability.
This fixes a problem I've had while trying to setup [Google LDAP](https://support.google.com/a/answer/9048516?hl=en) for the Jenkins instance I manage.
The initial request does not include the rootDN when connecting to `ldap.google.com`, which returns a 
`INSUFFICIENT_ACCESS_RIGHTS (50)` upon doing so. 
Including the DN directly in the URL of the LDAP server (like `ldaps://ldap.google.com/dc=example,dc=org`) also does not work, as its interpreted as an URL - therefore the requests turn into `dc=example,dc=org/`, which makes the user check fail at a later point.
> Include RootDN in doCheckServer

- src/test/java/hudson/security/LDAPSecurityRealmTest.java
https://github.com/jenkinsci/bom/pull/883#issuecomment-1041489253
Cannot reproduce test failure locally with Internet disabled, but do see warnings which would suggest that the test could actually hang under some network conditions:
<details>
```
WARNING	j.s.p.ldap.LDAPConfiguration#inferRootDN: Failed to connect to LDAP to infer Root DN for ldap.itd.umich.edu
java.net.UnknownHostException: ldap.itd.umich.edu
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
at …
at com.sun.jndi.ldap.Connection.createSocket(Connection.java:380)
at com.sun.jndi.ldap.Connection.<init>(Connection.java:220)
Caused: javax.naming.CommunicationException: ldap.itd.umich.edu:389 [Root exception is java.net.UnknownHostException: ldap.itd.umich.edu]
at …
```
> Do not connect to `ldap.itd.umich.edu` in tests

- src/main/resources/jenkins/security/plugins/ldap/LDAPConfiguration/help-groupSearchBase.html
The dangling bold tag in the groupSearchBase help file causes the configuration as code reference help to be bold text for about 50% of the page in my Jenkins installation.  End the bold tag on the same line that it was started so that other reference files that include it are not stuck with bold enabled.
I can submit a Jira issue if needed.  This seemed simple enough to not be worth the effort of a Jira issue.
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
> End the bold tag in groupSearchBase help file

- pom.xml
See [JENKINS-68462](https://issues.jenkins.io/browse/JENKINS-68462). The current version of this plugin bundles an old version of `spring-ldap-core`, which requires JAXB. When we start requiring Java 11, JAXB will not be available except as a plugin-to-plugin dependency (which this plugin does not have). In https://github.com/spring-projects/spring-ldap/issues/590 `spring-ldap-core` 2.3.5 and later stopped requiring JAXB. This PR updates the core baseline to 2.332.x, which pulls in a newer version of `spring-security-bom`, which pulls in `spring-ldap-core` 2.3.5 (2.303.x pulls in 2.3.4, sadly). Thus with this update we start shipping `spring-ldap-core` 2.3.5 which no longer depends on JAXB, and thus we are assured of a smooth upgrade for users when we start requiring Java 11.
```
$ mvn …
```
> [JENKINS-68462] Prepare LDAP for removal of JAXB and Java 11 requirement

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
[JENKINS-69056](https://issues.jenkins.io/browse/JENKINS-69056) fire authenticated event on authentication to notify SecurityListeners.
> [JENKINS-69056] fire authenticated event for SecurityListeners

- src/main/java/hudson/security/LDAPSecurityRealm.java
- src/test/java/hudson/security/LDAPEmbeddedTest.java
In order to enable audit of failed logins in the system, firing a corresponding event.
Jira: https://issues.jenkins.io/browse/JENKINS-2131
Related PR: https://github.com/jenkinsci/ldap-plugin/pull/164
> [JENKINS-2131] fire failedToAuthenticate event for SecurityListeners

- pom.xml
it's required for https://github.com/jenkinsci/jenkins/pull/7781 so that tests continue passing in this plugin and in bom, currently failing in https://github.com/jenkinsci/bom/pull/1968.
Can this be released please?
> Bump parent pom and bom

- src/main/resources/jenkins/security/plugins/ldap/validation/validate/validate.js
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I installed this plugin on a custom build of Jenkins that had Prototype ripped out (a local project branch), went to the Security page and tried to validate a …
> Replace Prototype.js with native JavaScript

- src/main/resources/hudson/security/LDAPSecurityRealm/config.jelly
The help of *Disable Backward Compatibility for Roles* shows an error instead of the help:
> ERROR: Failed to load help file: Not Found
With this PR the actual text is shown.
Local testing.
```[tasklist]
```
> Fix 'Disable Backward Compatibility for Roles' help

- src/main/resources/jenkins/security/plugins/ldap/validation/validate.jelly
The change proposed replaces the EOL spinner.gif with the drop-in Jelly tag replacement.
> Update EOL spinner.gif

- pom.xml
- src/main/resources/jenkins/security/plugins/ldap/validation/validate.jelly
- src/main/resources/jenkins/security/plugins/ldap/validation/validate/validate.js
- src/main/resources/jenkins/security/plugins/ldap/validation/validateButton.js
- src/main/resources/jenkins/security/plugins/ldap/validation/validateButtonOnClick.js
- src/test/java/hudson/security/LDAPEmbeddedTest.java
Updated the dialog design to remove dependency on YUI and improve theme support (https://github.com/jenkinsci/dark-theme-plugin/issues/142 ). Analogous to https://github.com/jenkinsci/credentials-plugin/pull/500
<details>
<summary>Screenshot</summary>
</details>
Checked that dialog displays OK and Test button validates the data. I don't have a proper LDAP server running so I wasn't able to get successful validation, just checked that the data being validated looks OK.
```[tasklist]
```
> Use new dialog design for validation dialog

- pom.xml
Simplify jsoup API version management by using the version from the plugin bill of materials.
This tests jsoup API 1.21.1 as also proposed in:
* #353 
Supersedes pull requests:
* #363
* #353
Updates the minimum required Jenkins version from 2.479.1 to 2.479.3 per ["Choosing a Jenkins version to build against"](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/)
Pull request should be labeled `tests` but I don't have permission to assign the label.
Confirmed that automated tests pass on Linux with Java 21.  Rely on ci.jenkins.io to test Windows and Java 17.
> Test with jsoup API plugin instead of jsoup library

- pom.xml
- src/test/resources/jenkins/security/plugins/ldap/LDAPSecurityRealmTestNoSecretExpected.yml
After the changes implemented on https://github.com/jenkinsci/configuration-as-code-plugin/pull/2712, there are some failing CasC test on the plugin:
com.cloudbees.jenkins.plugins.platform.CasCTest#smokeExport
The idea behind this PR is to upgrade the CasC plugin dependencies to 1995.v540b_50a_eb_0c1 and fix the failing tests.
> Fix Casc test failing after upgrading to CasC 1995.v540b_50a_eb_0c1
